### ISSUE TITLE
[BUG]: Copy to clipboard not working

### ISSUE THREAD

**Issue by Jenish-Dhanani** [Shariar-Hasan/QuoteVerse#63] opened 2023-10-18 14:07 UTC
### Kindly explain, what is the issue or what bug do you want to be fixed?

Greetings,

Following the integration of the animation code with the quote, there was a modification in the DOM structure of the quote body. Previously, it comprised a single element, whereas now each word is encapsulated within an individual HTML element. Consequently, when copying the quote text, it no longer replicates the quote text. This is a minor issue that I can address. Kindly assign it to me, and I will take care of the fix.

Expected:
"Persistence guarantees that results are inevitable."- Paramahansa Yogananda

Behaving:
`<span class="animate-text"><i style="animation-delay: 0s;">"Persistence</i></span> <span class="animate-text"><i style="animation-delay: 0.05s;">guarantees</i></span> <span class="animate-text"><i style="animation-delay: 0.1s;">that</i></span> <span class="animate-text"><i style="animation-delay: 0.15s;">results</i></span> <span class="animate-text"><i style="animation-delay: 0.2s;">are</i></span> <span class="animate-text"><i style="animation-delay: 0.25s;">inevitable."</i></span>- Paramahansa Yogananda
`

Appreciate it,
Jenish

### Screenshot of the issue.

Not an UI issue.

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] i am sure, this issue is not raised before.

### Do you want to fix the issue?

Yes, I want to fix it

**Comment by Shariar-Hasan** [comment] 2023-10-18 14:33
> yeap, thats a bug. you are assigned. feel free to contribute.

i am actually a bit busy, thats why i cant checked it properly.
the reason of the issue is because of worng conflict merged.

if you want to fix the issue, can you open a different issue for it?
if you do.
you have to mskr 2 diffrrent PR

**Closed** 2023-10-18 14:58 UTC
Labels: bug, hacktoberfest-accepted, hacktoberfest
