### ISSUE TITLE
[BUG]: Share Icons clashes with the Quotes Text 

### ISSUE THREAD

**Issue by shrutimishra27** [Shariar-Hasan/QuoteVerse#86] opened 2023-10-21 07:55 UTC
### Kindly explain, what is the issue or what bug do you want to be fixed?

I want to contribute in fixing this bug on this Repo under hacktoberfest label.

Bugs to be fixed:
- [ ] Align the share buttons horizontally
- [ ] Align the quotes text with share buttons when horizontally aligned

## Original:

<img width="960" alt="Screenshot 2023-10-21 123540" src="https://github.com/Shariar-Hasan/QuoteVerse/assets/96042938/e503313d-2fcd-4282-b3ac-f910adba7dcb">

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] i am sure, this issue is not raised before.

### Do you want to fix the issue?

Yes, I want to fix it

**Comment by shrutimishra27** [comment] 2023-10-21 08:08
@Shariar-Hasan , please check the PR created along with this issue.
Thanks.

**Comment by Shariar-Hasan** [comment] 2023-10-21 15:03
read the contribution guideline, and make another PR.

**Comment by shrutimishra27** [comment] 2023-10-21 15:11
Fine.
I starred the repository, forked it, cloned it, did the changes accordingly to create a PR.
Can you assign this issue to me so that now I can create PR according to the guidelines?

**Comment by Shariar-Hasan** [comment] 2023-10-21 15:33
no need to fork again,
you can make another PR with the same fork.
btw assigned now, rules are rules. 🙂

**Comment by KSSaiTeja** [comment] 2023-10-21 15:37
hi @Shariar-Hasan if the issue is still open i will fix it in less than one minute.. can i start work on this..?

**Comment by Shariar-Hasan** [comment] 2023-10-21 15:39
well, the issue is already assigned to @shrutimishra27

**Comment by KSSaiTeja** [comment] 2023-10-21 15:40
if it is ok for you.. i will start work right now.. and get it fix..

**Comment by Shariar-Hasan** [comment] 2023-10-21 15:43
> well, the issue is already assigned to @shrutimishra27

as i said, she is assigned already,
she already fixed it.
just have to make a PR.
well, if you find any other bug, you can create issue.
make sure to read the contribution guidelines

**Comment by KSSaiTeja** [comment] 2023-10-21 15:44
yeah sure..
Thanks for the quick replies..

**Comment by shrutimishra27** [comment] 2023-10-21 15:45
> no need to fork again, you can make another PR with the same fork. btw assigned now, rules are rules. 🙂

Yes yes I understand.
Will take extra care from next time.

**Closed** 2023-10-21 15:56 UTC
Labels: bug, hacktoberfest-accepted, hacktoberfest
